### ISSUE TITLE
How to modify code for continuous actions?

### ISSUE THREAD

**Issue by AjayTalati** [pfre00/a3c#1]
Hello :)

I really like your code, thanks a lot for sharing it. 

I want to modify it for continuous actions - and test it on openAI gym Mountain Car,

`env = gym.envs.make("MountainCarContinuous-v0")`

I'm confused though how to modify the code?

Here's what I've got so far,

```
# no need to use the conv layers as the state/obervation is only 2 floats !!!

self.lstm = nn.LSTMCell(2, lstm_out)

# modify actor_linear (model.py#L26) to return mu and sigma for a normal distribution
self.actor_mu = nn.Linear(lstm_out, 1)
self.actor_sigma = nn.Linear(lstm_out, 1)

# modify the output of  def forward(self, inputs):
return self.critic_linear(x), self.actor_mu(x), self.actor_sigma(x), (hx, cx)

# in train.py 
value, mu, sigma, (hx, cx) = local_model((Variable(state), (hx, cx)))

mu = mu.clamp(-1, 1) # constain to sensible values 
Softplus=nn.Softplus()     
sigma = Softplus(sigma) #+ 1e-5 # constain to sensible values
normal_dist = torch.normal(mu, sigma) 

prob = normal_dist
# TODO - it breaks here
nnlog = nn.Log() 
log_prob = nnlog(prob)

action = prob.data
action.clamp( env.action_space.low[0], env.action_space.high[0] ) # Atari specific clamping
action = Variable( action )
log_prob = log_prob.gather(1, action)
```

May I ask if you've tried this already and got it to work? Thanks for your help.

Best regards,

Aj

References,

Reference - Deepmind A3C's paper, https://arxiv.org/pdf/1602.01783.pdf
Section 9 - Continuous Action Control Using the MuJoCo Physics Simulator

![image](https://cloud.githubusercontent.com/assets/10279780/23881234/16de9b8c-0851-11e7-92af-9e08d57ec441.png)

from  https://github.com/deeplearninc/relaax#distributed-a3c-architecture-with-continuous-actions

**Comment by ethancaballero** [comment]
@AjayTalati How does this compare to https://github.com/ikostrikov/pytorch-a3c implementation? Does it perform better/worse/same on Breakout-v0?

**Comment by AjayTalati** [comment]
@ethancaballero, hello:)

Sorry, I don't know, I haven't really compared them on Breakout? 

I would think it depends on how non-stationary the reward signal is, RMSprop without sharing does well on some environments, async ADAM does well on other environments. Depending on your application you could just try both?

Hope this helps!

**Comment by ethancaballero** [comment]
Thanks @AjayTalati 
Also, do you no the answer to this question:
https://github.com/ikostrikov/pytorch-a3c/issues/6

**Comment by pfre00** [comment]
@AjayTalati I could not get it working with RMSprop, Adam works OK as long as there is no parameter sharing xD. Normalizing the inputs also messes learning up, which is pretty strange. I am working on the continuous action space implementation. I got it to learn, pretty unstable though. This seems to be the case with A3C overall.

**Comment by pfre00** [comment]
@ethancaballero The ikostrikov implementation does ~400 score. The best score I reached was around 250, using 4 threads, running the algorithm for 10 hours. Running for longer / using more threads could improve the results.

**Comment by AjayTalati** [comment]
@pfre00 Thank you very much ;)

I've got a thread in the PyTorch forum, 

https://discuss.pytorch.org/t/continuous-action-a3c/1033/3

about the continuous action space implementation - I'll try to update it with any progress. I made a mistake above - the DeepMind paper uses a ReLU encoder, before the LSTM.

There's a tensorflow implementation, which perhaps might be worth taking at look at? I guess this is the most relevant bit,

https://github.com/deeplearninc/relaax/blob/master/algorithms/da3c_cont/common/network.py#L48

Cheers, Aj

**Comment by pfre00** [comment]
@AjayTalati The value function loss is as usual.

For the policy loss, you can't just substitute the log probabiliy of the chosen action, since that is 0 in a continuous domain (infinitesimal point). Instead, you substitute the density function into the logarithm. This way, the logarithm and the exponent cancel out.

You get two terms: log(1/sqrt(2*sigma^2*pi)) - (x - mu)^2/(2*sigma^2)

If you have the multivariate distribution, you get the probability of your output by multiplying the density functions. Taking the logarithm of this results in a sum consisting of multiple instances of the above expression.

Calculation of the entropy is described in the paper.

I am pushing the continuous branch as soon as i get it working properly. It is learning, but keeps losing progress periodically. Probably tuning problems.

https://www.statlect.com/fundamentals-of-statistics/normal-distribution-maximum-likelihood

**Comment by AjayTalati** [comment]
@pfre00 Thank you very much again !!!

I think I understand the policy loss now :+1: , the magic of going from a product to a sum :+1: 

This is what I'm trying for the entropy, `entropy = 0.5 * (torch.log(2. * np.pi * sigma_sqrd ) + 1.)`

From Figure S7 on page 16 in the paper, https://arxiv.org/pdf/1602.01783.pdf, it seems most of their experiments did well with a learning rate of `pow(10,-4)`, so I'll try this as the default value.

**Comment by AjayTalati** [comment]
Hi @pfre00 :)

There's some discussion about grad and parameter sharing in @ikostrikov's implementation that I thought you might find interesting, 

https://github.com/ikostrikov/pytorch-a3c/commit/d4d003673df40a0e2b5c8ef5456300ea43c9853b

Maybe they've got it working?

**Comment by AjayTalati** [comment]
Hi, I wonder if you've managed to get it working?

I'm still stuck? Here's a post of my code 

https://gist.github.com/AjayTalati/184fec867380f6fa22b9aa0951143dec

I keep getting this error, 

```
File "main_single.py", line 174, in <module>
value_loss = value_loss + advantage.pow(2)
AttributeError: 'numpy.ndarray' object has no attribute 'pow'
```

I don't understand why `advantage` has become a `numpy` array instead of a `torch.tensor` - it never occurred with the discrete action implementation?

Any ideas what I've got wrong?

Thanks a lot for your help,

Ajay

**Comment by pfre00** [comment]
Flip the two terms in the addition where you calculate R. Make it g*R + r[t]. I had this problem too. R is a tensor and r[t] is a scalar afaik, so the result should be a tensor. It is a numpy array though. There is no problem with discrete actions. I haven't figured out what the difference is but flipping the terms has worked for me. I'll push the branch when I get home.

**Comment by AjayTalati** [comment]
Hello :) thanks a lot for your advice, I tried this

```
R =  args.gamma * R 
torch.add(R, rewards[t]) # in place addition by a constant
```

but now I get this error ???

```
  File "main_single.py", line 189, in <module>
    (policy_loss + 0.5 * value_loss).backward()
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/torch/autograd/variable.py", line 158, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/torch/autograd/stochastic_function.py", line 13, in _do_backward
    raise RuntimeError("differentiating stochastic functions requires "
RuntimeError: differentiating stochastic functions requires providing a reward
```
The code makes sense, I think maybe it's something to do with the `gym environment` ??? 

Anyway, it's cool that you got it working - I'll test your branch on different environments, and see if I can figure out where mine's broken, and maybe where we can make improvements :+1: 

Thanks a lot ,

Aj

**Comment by pfre00** [comment]
@AjayTalati I have pushed my implementation in the continuous_control branch. It is not fine tuned, but the calculations should be about right.

**Comment by pfre00** [comment]
@AjayTalati Btw, what I have said about the probability density function being 0 at any given point is false, it turns out it returns relative probabilities.

**Comment by AjayTalati** [comment]
Hi @pfre00 I just logged on! Thank you very much for pushing your continuous control implementation - it's really cool :+1: I'll start trying it on different environments, and give you feedback on how it's doing!

Best,

Ajay

**Comment by AjayTalati** [comment]
Hi @pfre00,

sorry for not getting back to you about trying continuous actions on different environments - I had to start working on something else, and I'm kind of swamped with that stuff now ??? 

I'll try to start doing experiments again this weekend.

Best,

Ajay

**Comment by pfre00** [comment]
Hi @AjayTalati ,
I am currently experimenting with the discrete version, reading materials and stuff. Thank you for your help.

**Comment by AjayTalati** [comment]
Hi @pfre00,

how it going? I think I'm going to follow your example and experiment with the discrete version - I'm not getting much luck with continuous actions? 

Also I want to see which environments `AsyncRMSprop` works better what `AsyncAdam`?

Could I ask your advice please? Last time I tried to use `AsyncRMSprop`, there was an error initialising the state, (after updating to the latest version of `PyTorch`), near this line,

https://github.com/pfre00/a3c/blob/master/async_rmsprop.py#L18

I tried to fix it, and also tried to copy `rarilurelo`'s version

https://github.com/rarilurelo/pytorch_a3c/blob/master/async_rmsprop.py

But neither worked - I don't understand where to get the `grad` from when initialising the `state`? 

Thanks a lot for your help :+1: 

Cheers,
Aj

**Comment by pfre00** [comment]
Hey @AjayTalati ,

I have pushed a few commits, the last one includes the shared rmsprop implementation. I have updated my pytorch version and done some other stuff, including changing the model. The current implementation is significantly slower than past ones. I am looking for the issue right now.

**Comment by pfre00** [comment]
By slower, I mean that learning is slower. Also, the last few versions have kept changing how parallelism works. Setting ```torch.set_num_threads(1)``` in the main thread used to work. Next version, I had to set this in every thread. Now I have to run ```OMP_NUM_THREADS=1 python main.py``` or else calculations are like 3 times slower.

**Comment by AjayTalati** [comment]
Hey,  @pfre00, cool!

Seems like in the new commits `train` is pretty much the same? So I guess maybe an alternative way to check the parallelism is to switch optimizer's in MNIST hogwild,

https://github.com/pytorch/examples/tree/master/mnist_hogwild

I'm not sure how independent environments, RL algorithms, models and parallelized optimization is. I guess the only way to test performance is to try? Hopefully we should be able to track down the reason for the change in learning speed?

Best,

Aj
